// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    user_id,
    account_number,
    account_type,
    balance,
    currency,
    status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) RETURNING id, user_id, account_number, account_type, balance, currency, status, version, created_at, updated_at
`

type CreateAccountParams struct {
	UserID        pgtype.UUID     `json:"user_id"`
	AccountNumber string          `json:"account_number"`
	AccountType   string          `json:"account_type"`
	Balance       decimal.Decimal `json:"balance"`
	Currency      string          `json:"currency"`
	Status        string          `json:"status"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg *CreateAccountParams) (*Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.UserID,
		arg.AccountNumber,
		arg.AccountType,
		arg.Balance,
		arg.Currency,
		arg.Status,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountNumber,
		&i.AccountType,
		&i.Balance,
		&i.Currency,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, user_id, account_number, account_type, balance, currency, status, version, created_at, updated_at
FROM accounts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (*Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountNumber,
		&i.AccountType,
		&i.Balance,
		&i.Currency,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getAccountByNumber = `-- name: GetAccountByNumber :one
SELECT id, user_id, account_number, account_type, balance, currency, status, version, created_at, updated_at
FROM accounts
WHERE account_number = $1
LIMIT 1
`

func (q *Queries) GetAccountByNumber(ctx context.Context, accountNumber string) (*Account, error) {
	row := q.db.QueryRow(ctx, getAccountByNumber, accountNumber)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountNumber,
		&i.AccountType,
		&i.Balance,
		&i.Currency,
		&i.Status,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listAccountsByUserID = `-- name: ListAccountsByUserID :many
SELECT id, user_id, account_number, account_type, balance, currency, status, version, created_at, updated_at
FROM accounts
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAccountsByUserID(ctx context.Context, userID pgtype.UUID) ([]*Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountNumber,
			&i.AccountType,
			&i.Balance,
			&i.Currency,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsWithLock = `-- name: ListAccountsWithLock :many
SELECT id, user_id, account_number, account_type, balance, currency, status, version, created_at, updated_at
FROM accounts
WHERE id = ANY($1::uuid[])
ORDER BY id
FOR UPDATE
`

func (q *Queries) ListAccountsWithLock(ctx context.Context, dollar_1 []pgtype.UUID) ([]*Account, error) {
	rows, err := q.db.Query(ctx, listAccountsWithLock, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountNumber,
			&i.AccountType,
			&i.Balance,
			&i.Currency,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE accounts
SET balance = $2,
    version = version + 1,
    updated_at = NOW()
WHERE id = $1
  AND version = $3
`

type UpdateAccountBalanceParams struct {
	ID      pgtype.UUID     `json:"id"`
	Balance decimal.Decimal `json:"balance"`
	Version int32           `json:"version"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg *UpdateAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, arg.ID, arg.Balance, arg.Version)
	return err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :exec
UPDATE accounts
SET status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateAccountStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg *UpdateAccountStatusParams) error {
	_, err := q.db.Exec(ctx, updateAccountStatus, arg.ID, arg.Status)
	return err
}
