// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Account struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	AccountNumber string             `json:"account_number"`
	AccountType   string             `json:"account_type"`
	Balance       decimal.Decimal    `json:"balance"`
	Currency      string             `json:"currency"`
	Status        string             `json:"status"`
	Version       int32              `json:"version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	ID              pgtype.UUID        `json:"id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	TransactionType string             `json:"transaction_type"`
	Amount          decimal.Decimal    `json:"amount"`
	BalanceAfter    decimal.Decimal    `json:"balance_after"`
	ReferenceID     pgtype.UUID        `json:"reference_id"`
	Description     pgtype.Text        `json:"description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Transfer struct {
	ID              pgtype.UUID        `json:"id"`
	FromAccountID   pgtype.UUID        `json:"from_account_id"`
	ToAccountID     pgtype.UUID        `json:"to_account_id"`
	Amount          decimal.Decimal    `json:"amount"`
	Currency        string             `json:"currency"`
	Status          string             `json:"status"`
	ReferenceNumber string             `json:"reference_number"`
	Description     pgtype.Text        `json:"description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
