// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg *CreateAccountParams) (*Account, error)
	CreateTransaction(ctx context.Context, arg *CreateTransactionParams) (*Transaction, error)
	CreateTransfer(ctx context.Context, arg *CreateTransferParams) (*Transfer, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetAccountByID(ctx context.Context, id pgtype.UUID) (*Account, error)
	GetAccountByNumber(ctx context.Context, accountNumber string) (*Account, error)
	GetTransactionByID(ctx context.Context, id pgtype.UUID) (*Transaction, error)
	GetTransactionsByReferenceID(ctx context.Context, referenceID pgtype.UUID) ([]*Transaction, error)
	GetTransferByID(ctx context.Context, id pgtype.UUID) (*Transfer, error)
	GetTransferByReference(ctx context.Context, referenceNumber string) (*Transfer, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (*User, error)
	ListAccountsByUserID(ctx context.Context, userID pgtype.UUID) ([]*Account, error)
	ListAccountsWithLock(ctx context.Context, dollar_1 []pgtype.UUID) ([]*Account, error)
	ListPendingTransfers(ctx context.Context, limit int32) ([]*Transfer, error)
	ListTransactionsByAccountID(ctx context.Context, arg *ListTransactionsByAccountIDParams) ([]*Transaction, error)
	ListTransactionsByAccountIDAndType(ctx context.Context, arg *ListTransactionsByAccountIDAndTypeParams) ([]*Transaction, error)
	ListTransactionsByDateRange(ctx context.Context, arg *ListTransactionsByDateRangeParams) ([]*Transaction, error)
	ListTransactionsByDateRangeAndType(ctx context.Context, arg *ListTransactionsByDateRangeAndTypeParams) ([]*Transaction, error)
	ListTransfersByAccount(ctx context.Context, arg *ListTransfersByAccountParams) ([]*Transfer, error)
	ListUsers(ctx context.Context, arg *ListUsersParams) ([]*User, error)
	UpdateAccountBalance(ctx context.Context, arg *UpdateAccountBalanceParams) error
	UpdateAccountStatus(ctx context.Context, arg *UpdateAccountStatusParams) error
	UpdateTransferStatus(ctx context.Context, arg *UpdateTransferStatusParams) error
	UpdateUser(ctx context.Context, arg *UpdateUserParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
