// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (
    from_account_id,
    to_account_id,
    amount,
    currency,
    status,
    reference_number,
    description
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
) RETURNING id, from_account_id, to_account_id, amount, currency, status, reference_number, description, created_at, completed_at
`

type CreateTransferParams struct {
	FromAccountID   pgtype.UUID     `json:"from_account_id"`
	ToAccountID     pgtype.UUID     `json:"to_account_id"`
	Amount          decimal.Decimal `json:"amount"`
	Currency        string          `json:"currency"`
	Status          string          `json:"status"`
	ReferenceNumber string          `json:"reference_number"`
	Description     pgtype.Text     `json:"description"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg *CreateTransferParams) (*Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.ReferenceNumber,
		arg.Description,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ReferenceNumber,
		&i.Description,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return &i, err
}

const getTransferByID = `-- name: GetTransferByID :one
SELECT id, from_account_id, to_account_id, amount, currency, status, reference_number, description, created_at, completed_at
FROM transfers
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTransferByID(ctx context.Context, id pgtype.UUID) (*Transfer, error) {
	row := q.db.QueryRow(ctx, getTransferByID, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ReferenceNumber,
		&i.Description,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return &i, err
}

const getTransferByReference = `-- name: GetTransferByReference :one
SELECT id, from_account_id, to_account_id, amount, currency, status, reference_number, description, created_at, completed_at
FROM transfers
WHERE reference_number = $1
LIMIT 1
`

func (q *Queries) GetTransferByReference(ctx context.Context, referenceNumber string) (*Transfer, error) {
	row := q.db.QueryRow(ctx, getTransferByReference, referenceNumber)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.ReferenceNumber,
		&i.Description,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return &i, err
}

const listPendingTransfers = `-- name: ListPendingTransfers :many
SELECT id, from_account_id, to_account_id, amount, currency, status, reference_number, description, created_at, completed_at
FROM transfers
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingTransfers(ctx context.Context, limit int32) ([]*Transfer, error) {
	rows, err := q.db.Query(ctx, listPendingTransfers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.ReferenceNumber,
			&i.Description,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersByAccount = `-- name: ListTransfersByAccount :many
SELECT id, from_account_id, to_account_id, amount, currency, status, reference_number, description, created_at, completed_at
FROM transfers
WHERE from_account_id = $1
   OR to_account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransfersByAccountParams struct {
	FromAccountID pgtype.UUID `json:"from_account_id"`
	Limit         int32       `json:"limit"`
	Offset        int32       `json:"offset"`
}

func (q *Queries) ListTransfersByAccount(ctx context.Context, arg *ListTransfersByAccountParams) ([]*Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersByAccount, arg.FromAccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.FromAccountID,
			&i.ToAccountID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.ReferenceNumber,
			&i.Description,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransferStatus = `-- name: UpdateTransferStatus :exec
UPDATE transfers
SET status = $2,
    completed_at = CASE
        WHEN $2 = 'completed' THEN NOW()
        ELSE completed_at
    END
WHERE id = $1
`

type UpdateTransferStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateTransferStatus(ctx context.Context, arg *UpdateTransferStatusParams) error {
	_, err := q.db.Exec(ctx, updateTransferStatus, arg.ID, arg.Status)
	return err
}
