// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    account_id,
    transaction_type,
    amount,
    balance_after,
    reference_id,
    description
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
) RETURNING id, account_id, transaction_type, amount, balance_after, reference_id, description, created_at
`

type CreateTransactionParams struct {
	AccountID       pgtype.UUID     `json:"account_id"`
	TransactionType string          `json:"transaction_type"`
	Amount          decimal.Decimal `json:"amount"`
	BalanceAfter    decimal.Decimal `json:"balance_after"`
	ReferenceID     pgtype.UUID     `json:"reference_id"`
	Description     pgtype.Text     `json:"description"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg *CreateTransactionParams) (*Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.AccountID,
		arg.TransactionType,
		arg.Amount,
		arg.BalanceAfter,
		arg.ReferenceID,
		arg.Description,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransactionType,
		&i.Amount,
		&i.BalanceAfter,
		&i.ReferenceID,
		&i.Description,
		&i.CreatedAt,
	)
	return &i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, account_id, transaction_type, amount, balance_after, reference_id, description, created_at
FROM transactions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id pgtype.UUID) (*Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransactionType,
		&i.Amount,
		&i.BalanceAfter,
		&i.ReferenceID,
		&i.Description,
		&i.CreatedAt,
	)
	return &i, err
}

const getTransactionsByReferenceID = `-- name: GetTransactionsByReferenceID :many
SELECT id, account_id, transaction_type, amount, balance_after, reference_id, description, created_at
FROM transactions
WHERE reference_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetTransactionsByReferenceID(ctx context.Context, referenceID pgtype.UUID) ([]*Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByReferenceID, referenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TransactionType,
			&i.Amount,
			&i.BalanceAfter,
			&i.ReferenceID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccountID = `-- name: ListTransactionsByAccountID :many
SELECT id, account_id, transaction_type, amount, balance_after, reference_id, description, created_at
FROM transactions
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByAccountIDParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListTransactionsByAccountID(ctx context.Context, arg *ListTransactionsByAccountIDParams) ([]*Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByAccountID, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TransactionType,
			&i.Amount,
			&i.BalanceAfter,
			&i.ReferenceID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByAccountIDAndType = `-- name: ListTransactionsByAccountIDAndType :many
SELECT id, account_id, transaction_type, amount, balance_after, reference_id, description, created_at
FROM transactions
WHERE account_id = $1
  AND transaction_type = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListTransactionsByAccountIDAndTypeParams struct {
	AccountID       pgtype.UUID `json:"account_id"`
	TransactionType string      `json:"transaction_type"`
	Limit           int32       `json:"limit"`
	Offset          int32       `json:"offset"`
}

func (q *Queries) ListTransactionsByAccountIDAndType(ctx context.Context, arg *ListTransactionsByAccountIDAndTypeParams) ([]*Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByAccountIDAndType,
		arg.AccountID,
		arg.TransactionType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TransactionType,
			&i.Amount,
			&i.BalanceAfter,
			&i.ReferenceID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByDateRange = `-- name: ListTransactionsByDateRange :many
SELECT id, account_id, transaction_type, amount, balance_after, reference_id, description, created_at
FROM transactions
WHERE account_id = $1
  AND created_at >= $2
  AND created_at <= $3
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListTransactionsByDateRangeParams struct {
	AccountID   pgtype.UUID        `json:"account_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Limit       int32              `json:"limit"`
	Offset      int32              `json:"offset"`
}

func (q *Queries) ListTransactionsByDateRange(ctx context.Context, arg *ListTransactionsByDateRangeParams) ([]*Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByDateRange,
		arg.AccountID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TransactionType,
			&i.Amount,
			&i.BalanceAfter,
			&i.ReferenceID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByDateRangeAndType = `-- name: ListTransactionsByDateRangeAndType :many
SELECT id, account_id, transaction_type, amount, balance_after, reference_id, description, created_at
FROM transactions
WHERE account_id = $1
  AND created_at >= $2
  AND created_at <= $3
  AND transaction_type = $4
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type ListTransactionsByDateRangeAndTypeParams struct {
	AccountID       pgtype.UUID        `json:"account_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2     pgtype.Timestamptz `json:"created_at_2"`
	TransactionType string             `json:"transaction_type"`
	Limit           int32              `json:"limit"`
	Offset          int32              `json:"offset"`
}

func (q *Queries) ListTransactionsByDateRangeAndType(ctx context.Context, arg *ListTransactionsByDateRangeAndTypeParams) ([]*Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByDateRangeAndType,
		arg.AccountID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.TransactionType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TransactionType,
			&i.Amount,
			&i.BalanceAfter,
			&i.ReferenceID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
